### ISSUE TITLE
I face this error in data_prepare, how to solve this?

### ISSUE THREAD

**Issue by AnwarsaeedDMU** [Anery/RSAN#12]
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\faiz papers\new\RSAN-master\data_prepare.py", line 256, in <module>
    Prepare.prepare()
  File "C:\Users\Usuario\Desktop\faiz papers\new\RSAN-master\data_prepare.py", line 52, in prepare
    dev_f, dev_l = self.process_dev_test(self.dev_data)
  File "C:\Users\Usuario\Desktop\faiz papers\new\RSAN-master\data_prepare.py", line 119, in process_dev_test
    return np.array(features), np.array(sen_len)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (5000, 4) + inhomogeneous part.

**Comment by Ariel-lu** [comment]
@AnwarsaeedDMU Hello,have you solved this problem
