### ISSUE TITLE
在webnlg数据集上训练RSAN出错

### ISSUE THREAD

**Issue by wwwwwwwwf** [Anery/RSAN#7]
您好，我非常关注您的工作。然而，我在webnlg数据集上训练RSAN时发生以下错误：

`Traceback (most recent call last):
  File "train.py", line 163, in <module>
    train(opt)
  File "train.py", line 79, in train
    predictions, targets, _ ,metrics = eval_utils.evaluate(Model, loader, infos['label2id'], opt.eval_batch_size, opt.rel_num, 'dev')
  File "/home/lwf/NLU/RSAN-master/eval_utils.py", line 67, in evaluate
    triple = tag_mapping(decode_tags[i * (rel_num - 1):(i + 1) * (rel_num - 1)], current_relation, label2id)
  File "/home/lwf/NLU/RSAN-master/misc/utils.py", line 131, in tag_mapping
    pred_chunks = get_chunks(predict_tags[i], label2id)
  File "/home/lwf/NLU/RSAN-master/misc/utils.py", line 93, in get_chunks
    res = get_chunk_type(tok, idx_to_tag)
  File "/home/lwf/NLU/RSAN-master/misc/utils.py", line 54, in get_chunk_type
    tag_name = idx_to_tag[tok]
KeyError: 13
`
您的label一共有{"S-H": 0, "S-T": 1, "B-H": 2, "B-T": 3, "I-H": 4, "I-T": 5, "E-H": 6, "E-T": 7, "O": 8, "X": 9}共10个，我不知道13这个数字到底是从哪里来的，希望您有时间的时候能够帮助我解决这个问题。谢谢您！

**Comment by Anery** [comment]
你好，我看了下发现webnlg里的config.py中label_num参数误设成了14 你可以把它改成10再试一下 如果还有问题我就再细看下代码
